apiVersion: v1
kind: Service
metadata:
  name: temporal-money-transfer-worker-activity-service
  namespace: temporal-money-transfer
  labels:
    app: temporal-money-transfer-worker-activity
spec:
  ports:
    - name: metrics
      port: 9090
      protocol: TCP
      targetPort: metrics
  type: ClusterIP
  selector:
    app: temporal-money-transfer-worker-activity
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
   name: temporal-money-transfer-worker-activity-servicemonitor
   namespace: temporal-money-transfer
spec:
   namespaceSelector:
      matchNames:
      - temporal-money-transfer
   selector:
      matchLabels:
         app: temporal-money-transfer-worker-activity
   endpoints:
      - port: metrics
