apiVersion: v1
kind: Service
metadata:
  name: temporal-money-transfer-server-service
  namespace: temporal-money-transfer
  labels:
    app: temporal-money-transfer-server
spec:
  ports:
  - port: 80
    name: server
  - port: 9090
    name: metrics  
    protocol: TCP
    targetPort: metrics
  type: ClusterIP
  selector:
    app: temporal-money-transfer-server
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
   name: temporal-money-transfer-server-servicemonitor
   namespace: temporal-money-transfer
spec:
   namespaceSelector:
      matchNames:
      - temporal-money-transfer
   selector:
      matchLabels:
         app: temporal-money-transfer-server
   endpoints:
      - port: metrics
