apiVersion: v1
kind: Service
metadata:
  name: temporal-money-transfer-worker-service
  namespace: temporal-money-transfer
  labels:
    app: temporal-money-transfer-worker
spec:
  ports:
    - name: metrics
      port: 9090
      protocol: TCP
      targetPort: metrics
  type: ClusterIP
  selector:
    app: temporal-money-transfer-worker
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
   name: temporal-money-transfer-worker-servicemonitor
   namespace: temporal-money-transfer
spec:
   namespaceSelector:
      matchNames:
      - temporal-money-transfer
   selector:
      matchLabels:
         app: temporal-money-transfer-worker
   endpoints:
      - port: metrics
