apiVersion: apps/v1
kind: Deployment
metadata:
  name: temporal-money-transfer-worker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: temporal-money-transfer-worker
  template:
    metadata:
      labels:
        app: temporal-money-transfer-worker
        namespace: temporal-money-transfer
    spec:
      containers:
        - name: worker-workflow
          image: steveandroulakis/temporal-moneytransfer-worker:latest
          imagePullPolicy: Always
          env:
            - name: WORKER_TYPE
              value: workflow
            - name: ADDRESS
              value: temporal-server-frontend-headless.stevea-temporal-server:7233
            - name: NAMESPACE
              value: default
            - name: NODE_ENV
              value: production
            - name: PROMETHEUS_ADDRESS
              value: 0.0.0.0:9090
            - name: STRIPE_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: stripe-secret-key
                  key: STRIPE_SECRET_KEY
          ports:
            - name: metrics
              containerPort: 9090