apiVersion: apps/v1
kind: Deployment
metadata:
  name: temporal-money-transfer-ui
  namespace: temporal-money-transfer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: temporal-money-transfer-ui
  template:
    metadata:
      labels:
        app: temporal-money-transfer-ui
    spec:
      containers:
      - name: ui
        image: steveandroulakis/temporal-moneytransfer-ui:latest
        imagePullPolicy: Always
        ports:
        - name: ui
          containerPort: 80
        env:
        - name: PORT
          value: "80"